"""Initial schema + row-level security + application role.

Revision ID: 0001
Revises: None

Bootstrap migration: creates all core tables from the model metadata, then layers on the
security that makes multi-tenancy real:

1. A **non-superuser application role** ``chartwright_app`` with table-level DML grants
   but no DDL. The admin role (table owner) is for migrations only — Postgres superusers
   bypass RLS, so the app must never connect as it.
2. **RLS enabled + FORCED** on every tenant-owned table, with policies keyed to
   ``current_setting('app.current_tenant', true)``. No context -> no rows.
3. ``audit_log`` gets INSERT/SELECT only for the app role — the append-only property is
   enforced by *withholding* UPDATE/DELETE grants, not by convention.

Note: this bootstrap revision builds tables from model metadata (create_all); subsequent
revisions use explicit autogenerated operations so diffs stay reviewable.
"""

from __future__ import annotations

from alembic import op
from chartwright_db.models import RLS_TABLES, Base

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None

APP_ROLE = "chartwright_app"
APP_ROLE_PASSWORD = "app_dev"  # noqa: S105 - dev-only; real envs override via ALTER ROLE


def upgrade() -> None:
    bind = op.get_bind()

    # 1) Tables from model metadata (bootstrap only; see module docstring).
    Base.metadata.create_all(bind=bind)

    # 2) Application role (idempotent).
    op.execute(
        f"""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '{APP_ROLE}') THEN
                CREATE ROLE {APP_ROLE} LOGIN PASSWORD '{APP_ROLE_PASSWORD}';
            END IF;
        END
        $$;
        """
    )
    op.execute(f"GRANT USAGE ON SCHEMA public TO {APP_ROLE}")
    op.execute(f"GRANT SELECT ON tenants TO {APP_ROLE}")  # read-only isolation root
    for table in RLS_TABLES:
        if table == "audit_log":
            # Append-only: no UPDATE/DELETE grant, so the property is DB-enforced.
            op.execute(f"GRANT SELECT, INSERT ON {table} TO {APP_ROLE}")
        else:
            op.execute(f"GRANT SELECT, INSERT, UPDATE, DELETE ON {table} TO {APP_ROLE}")

    # 3) RLS on every tenant-owned table. FORCE so even the owner obeys when not superuser.
    for table in RLS_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY tenant_isolation_{table} ON {table}
                USING (tenant_id = current_setting('app.current_tenant', true)::uuid)
                WITH CHECK (tenant_id = current_setting('app.current_tenant', true)::uuid)
            """
        )


def downgrade() -> None:
    bind = op.get_bind()
    for table in RLS_TABLES:
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation_{table} ON {table}")
    op.execute(f"REASSIGN OWNED BY {APP_ROLE} TO CURRENT_USER")
    op.execute(f"DROP OWNED BY {APP_ROLE}")
    op.execute(f"DROP ROLE IF EXISTS {APP_ROLE}")
    Base.metadata.drop_all(bind=bind)
